[package]
authors = ["Christopher Brickley <brickley@gmail.com>"]
description = "A rust crate for sending messages to Slack via webhooks."
homepage = "https://github.com/frostly/rust-slack"
keywords = ["slack", "webhook", "hook", "messaging"]
license = "MIT/Apache-2.0"
name = "slack-hook"
readme = "README.md"
repository = "https://github.com/frostly/rust-slack"
version = "0.8.0"
edition = "2018"

[dependencies]
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
hex = "0.4"
error-chain = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
# Used to access some functionality that isn't directly rexposed by `reqwest`
url = { version = "2.2", features = ["serde"] }
